My Portfolio
eric2umeh/portfolio-html-css pull request #9
Opened 2022-12-08 13:24 UTC by eric2umeh

- completed the web version of the portfolio
- checked for linter errors

2022-12-08 13:54 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @eric2umeh 👋 
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  

<img src="https://media3.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights:  
* All tests passed ✔️
* Professional README file ✔️

## Required Changes:

- [ ] Kindly add the MIT file to your project, the link in the README file is broken 😓 
- [ ] Kindly try to follow best  practices when you write commit messages, they should be capitalized sentences in the imperative form, example: "Add linters" instead of "added linters" 👍 

NOTE: there isn't alot of the code in the changed files so I'll leave the comments here instead of inline comments 👍 

- [ ] Kindly add `font-family` to your texts to match the design in Figma 👍 

### Your design:
![image](https://user-images.githubusercontent.com/50721479/206462037-c5ed688f-d341-4c49-8bfe-5a68c75a5f22.png)

### Figma design:
![image](https://user-images.githubusercontent.com/50721479/206462075-91604ab5-795c-4d68-a113-5861e27fe993.png)

- [ ] Kindly match the navbar of the Figma design, yours is lacking some space on the top, the logo should be bolder and the yellow underline in `portfolio` should not be there 👍 

### Your design:
![image](https://user-images.githubusercontent.com/50721479/206462302-2d01e815-c2fd-4356-8c4c-e02f51487adf.png)

### Figma design:
![image](https://user-images.githubusercontent.com/50721479/206462334-c943f51a-bac9-4a70-b305-b269a0a3cd1b.png)

- [ ] Kindly increase the size of the project images, in the cards where the image is on the right the text should be aligned to the left instead of to the right. Kindly fix these issues 💯 

### Your design:
![image](https://user-images.githubusercontent.com/50721479/206462556-b27712f5-e47d-4725-bf65-120b390f282c.png)

### Figma design:
![image](https://user-images.githubusercontent.com/50721479/206462667-c719bc41-71a4-408f-82c2-a9120bc33165.png)

- [ ] Kindly add some space between the left part and the right part to improve visibility and to match the design in Figma 👍 

### Your design:
![image](https://user-images.githubusercontent.com/50721479/206462884-54ba0307-15fe-4c8d-b571-745c1fdde56c.png)

### Figma design:
![image](https://user-images.githubusercontent.com/50721479/206462970-fb24357a-8141-4912-9aea-96a2e0f7c0af.png)

- [x] Kindly reduce the `width` of the little languages cards, and please add some `padding-bottom` to it to match the design in Figma 👍 

### Your design:
![image](https://user-images.githubusercontent.com/50721479/206463187-11182103-5c4c-48ce-9272-63ceacd5d57c.png)

### Figma design:
![image](https://user-images.githubusercontent.com/50721479/206463306-d98df8fc-63dc-469f-bcea-eca7d9ec033a.png)

- [x] Kindly add the missing arrow icon at the end of this part 👍 

### Your design: 
![image](https://user-images.githubusercontent.com/50721479/206463512-f8c3c693-7c62-4d59-aad6-6b1e3631cf4e.png)

### Figma design:
![image](https://user-images.githubusercontent.com/50721479/206463567-63f3966e-6697-4d6d-aecc-df57c5858896.png)

- [x] Kindly reduce the size of the input fields to match the design in Figma 👍 

### Your design:
![image](https://user-images.githubusercontent.com/50721479/206463760-93f4011b-19ee-45fe-9e35-ac60d4a33710.png)

### Figma design:
![image](https://user-images.githubusercontent.com/50721479/206463817-4b1413ea-4265-4216-82dd-1e9e2cb7f7d7.png)




------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 19:06 UTC, PinkMoon25 requested changes
Hi @eric2umeh , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media2.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

 ## Highlights
linters checks :heavy_check_mark: 
follows figma design :heavy_check_mark: 
used flex and grid :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 19:06 UTC, pinkmoon25 commented on README.md
- [x] As requested by the previous reviewer, please fix the MIT link in your readme as currently it is giving a 404 error, you have coorectly added the MIT.md file but you have not changed the link here :point_right: `This project is [MIT](./LICENSE) licensed.` change the link to be` ./MIT.md`

2022-12-08 19:06 UTC, PinkMoon25 commented on index.html
>              <div class="item2">
- [ ] As requested by the previous reviewer please make sure our project cards follow the figma template your design :point_down:  the buttons sre not in the right place
![image](https://user-images.githubusercontent.com/97521557/206544648-23913ee7-c7b4-4bae-931b-493b8993881e.png)
 
figma design :point_down: 
![image](https://user-images.githubusercontent.com/97521557/206544822-8e2b369c-1248-4cda-a310-eedf08cc111b.png)

2022-12-09 08:23 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @eric2umeh 

Your project is complete! Great job for making the requested changes 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request✔️ 
- Responsive site✔️ 
- Design well followed ✔️ 
- No linter errors✔️ 

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 08:25 UTC, merged